#!/bin/bash 

test_bash_unit_accepts_tap_format_option() {
  assert "$BASH_UNIT -f tap"
}

test_bash_unit_rejects_invalid_format() {
  assert_fail "$BASH_UNIT -f invalid_format"
}

test_tap_format_for_one_succesfull_test() {
  assert_equals \
"\
#      Running tests in code
ok     test_ok" \
\
"$(bash_unit_out_for_code <<EOF
  test_ok() {
    assert true
  }
EOF
)"
}

bash_unit_out_for_code() {
  $BASH_UNIT -f tap <(cat) | sed -e 's:/dev/fd/[0-9]*:code:g'
}

BASH_UNIT=../bash_unit
